### PR TITLE
Update vibi_views.sql

### PR DESCRIPTION
**Pull request by jreinier**

### CODE REVIEW

**Comment by nmco** [comment]
I'm guessing that the new calculations views (alt) should substitute the old ones ? If this is the case can you remove the calculations views that are deprecated. Thank you.

**Comment by jreinier** [comment]
We want both the old and new "alt" calculations kept.  While the original calculations should be visible to all viewers of the web page, the alt calculations should be restricted to only those users with higher levels of access.  At this point the alt calculations are mostly for internal use for Cleveland Metroparks staff.

**Comment by nmco** [comment]
I we follow the same logic that we used for the others calculations, I guess that the alternate calculations that should be show in the frontend are:

- alt_herbaceous_relative_cover 
- alt_woody_importance_value
- alt_metric_calculations

**Comment by jreinier** [comment]
Yes

**Pull request merged**
